Description of create_HD_nest_bdy_TYPE3
Home > fvcom_prepro > create_HD_nest_bdy_TYPE3.m
create_HD_nest_bdy_TYPE3
PURPOSE
Read in AMM data and interpolate onto the boundary of FVCOM model
SYNOPSIS
This is a script file.
DESCRIPTION
 Read in AMM data and interpolate onto the boundary of FVCOM model
 subname = 'create_HD_nest_bdy_TYPE3'
 DESCRIPTION:
    READ in the following data:
          - AMM data
        - FVCOM Grid file (connectivity + nodes)
       - list of nesting nodes created using create_nesting_nodes.m
    Process data:
       - Interpolate AMM data onto the FVCOM model nested boundary nodes
    Write output
       - Write interpolated elevation, speeds, T and S data  to Netcdf  nesting file
 INPUT [keyword pairs]:
   modify>>>>> 'gridfile'  = fvcom mesh file
 OUTPUT:
   modify>>>>>  Mobj = matlab structure containing mesh data
 EXAMPLE USAGE
    create_wave_bdy
 Author(s):
    Darren Price (CH2MHILL, Warrington, UK)
    Hakeem Johnson (CH2MHILL, Warrington, UK)
 Revision history
   Nov 2013: Initial version - not in the correct nesting file format
   Jan 2014: Beta version including the correct nesting format
   Mar 2014: HKJ
       - Corrected various bugs in connection with wave direction calcs..
       - Added 2 new functions: get_UxUy_DirFrom.m & get_DirFrom_UxUy.m
   2014:   DMP changed to use for HD nested boundaries
==============================================================================
CROSS-REFERENCE INFORMATION
This function calls:
get_HD_OBC Extract open boundary nodes from open boundary cordinate file
get_HD_nesting_nodes Extract open boundary nodes from open boundary cordinate file
read_fvcom_bath Read fvcom bathymetry file
write_nesting_bdy_file Write an FVCOM time series forcing file
This function is called by:
SOURCE CODE
% Read in AMM data and interpolate onto the boundary of FVCOM model
% subname = 'create_HD_nest_bdy_TYPE3'
%
% DESCRIPTION:
%    READ in the following data:
%          - AMM data
%        - FVCOM Grid file (connectivity + nodes)
%       - list of nesting nodes created using create_nesting_nodes.m
%    Process data:
%       - Interpolate AMM data onto the FVCOM model nested boundary nodes
%
%    Write output
%       - Write interpolated elevation, speeds, T and S data  to Netcdf  nesting file
%
% INPUT [keyword pairs]:
%   modify>>>>> 'gridfile'  = fvcom mesh file
%
% OUTPUT:
%   modify>>>>>  Mobj = matlab structure containing mesh data
%
% EXAMPLE USAGE
%    create_wave_bdy
%
% Author(s):
%    Darren Price (CH2MHILL, Warrington, UK)
%    Hakeem Johnson (CH2MHILL, Warrington, UK)
%
% Revision history
%   Nov 2013: Initial version - not in the correct nesting file format
%   Jan 2014: Beta version including the correct nesting format
%   Mar 2014: HKJ
%       - Corrected various bugs in connection with wave direction calcs..
%       - Added 2 new functions: get_UxUy_DirFrom.m & get_DirFrom_UxUy.m
%   2014:   DMP changed to use for HD nested boundaries
%==============================================================================
% clear
%%
%create nesting nodes - commented out here as run seperately during
%debugging
% create_nesting_nodes;
%%
clear all;
subname = 'create_HD_nest_bdy';
global ftbverbose;
if(ftbverbose);
  fprintf('\n')
  fprintf(['begin : ' subname '\n'])
end
%%
%---------------------------------------------------------
% user specify input data & parameters ...
%---------------------------------------------------------
% work & data folders ...
% directories default values
FVCOM_root = '\\hand-fs-01\maritime\Projects\Scottish Waters\Calcs\Models\WLLS\mesh10\nesting\';
cd(FVCOM_root);
workDir='\\hand-fs-01\maritime\Projects\Scottish Waters\Calcs\Models\WLLS\mesh10\nesting\';
dataDir='\\hand-fs-01\maritime\Projects\Scottish Waters\Calcs\Models\WLLS\mesh10\mesh\';
% AMMDir='C:\Users\iapostol\Documents\Miscellaneous_IGA\ApostolidouIG\Modelling\ScottishWaters\AMM_2011\';
AMMDir='\\uwa2v1th5j\Scottish_waters_mainbackup\Scottish_Waters\Scottish_Waters_AMM_2011\'; %external hard disk
%AMMDir='C:\PROJECTS\WLLS\AMM_2011\';
%AMMDir='X:\Scottish_Waters\Scottish_Waters_AMM_2011\';
disp('hard coded in time shift back 24.5 hours ');
shift=-24.5/24;  %shift found in results for ramWLLS_3
nsiglay=10;
basename = 'WLLS_v3smth';
meshFile=[basename '_grd.dat'];
bathFile=[basename '_dep.dat'];
obcFile=[basename '_node_nest.dat'];
bdyobcFile=[basename '_obc.dat'];
% output file
HDFile = [basename '2011May_10fshift24p5hours_coldstart_node_nest.nc'];
MyTitle=['WLLS model boundary conditions for mesh' meshFile];
    % define weighting for type 3 nesting
    % in this case we are only using one element width with weights on the
    % nodes on boundary and on other nodes on the elements on boundary
    weight_node1=0.75; %on boundary
    weight_node2=0.25; %inside boundary
    weight_elem_val=0.5;
    NEST_TYPE='TYPE3';
% set start & end time
StartDate = [2011,05,01,1,0,0]; %n.b start and end dates not used all data is written
EndDate   = [2011,05,30,1,0,0];  % changed from: [2009,12,31,21,00,0]
%EndDate   = [2011,05,3,8,0,0];  %---------------------------------------------------------
%smooth introduction  (similar to iramp, but for velocities and temp/salinity - was required for initial shock due to velocity being introduced  not all models require this though)
 smoothtime= 12.0; % number of hours in which to introduce forcing lineary
    speed_init=0;  % initial conditions
    salinity_init=35.0;
    temp_init=10.0;
    surfaceElevation_init=0.0;
% set full file names ...
%---------------------------------------------------------
meshFile     = [dataDir meshFile];
bathFile     = [dataDir bathFile];
obcFile      = [workDir obcFile];
bdyobcFile   = [dataDir bdyobcFile];
HDFile     = [workDir HDFile];
%%
%---------------------------------------------------------
% Read data into matlab
% 1) grid mesh; 2)boundary nodes; 3) UKMO data files  ...
%---------------------------------------------------------
% get fvcom grid file in as mesh object ...
FV_Mesh = read_fvcom_mesh_lonlat(meshFile);        % ... from matlab toolbox
FV_Mesh.have_bath = true;
FV_Mesh.h = read_fvcom_bath(bathFile);
% get  nesting nodes and associated lat/lon coord file
FV_OBC = get_HD_nesting_nodes(obcFile);
for i=1:FV_OBC.nVerts
    inode = FV_OBC.nnodesID(i);
    FV_OBC.lon(i) = FV_Mesh.lon(inode);
    FV_OBC.lat(i) = FV_Mesh.lat(inode);
    FV_OBC.h(i) = FV_Mesh.h(inode);
end
FV_OBC.x = FV_OBC.lon;   % temp solution
FV_OBC.y = FV_OBC.lat;   % temp solution
figure(1);
scatter(FV_OBC.lon,FV_OBC.lat,5,FV_OBC.h);shading flat;caxis([0 100]);colorbar;
%---------------------------------------------------------------------
% get elements at boundary & element centres
%---------------------------------------------------------------------
% get elements at boundary
T = FV_Mesh.tri;
X1 = FV_Mesh.lon;
Y1 = FV_Mesh.lat;
P = [X1,Y1];
TR = triangulation(T,P);
vi = FV_OBC.nnodesID;
ti = vertexAttachments(TR,vi);
% arrange data in one row (i.e. several columns); since elements overlap, get unique elements
temp1 = [ti{:}]';
%bdcell = temp1(temp1~=0);
bdcell = unique(temp1,'stable');
nCells = length(bdcell);
% get elements at boundary that have nodes in the supplied wave node
% nesting file..
kElem = 0;
for i=1:nCells
    ielem = bdcell(i);
    v(1) = FV_Mesh.tri(ielem,1);
    v(2) = FV_Mesh.tri(ielem,2);
    v(3) = FV_Mesh.tri(ielem,3);
    chk2 = ismember(v(1:3),vi);
    if(sum(chk2) == 3)
        kElem = kElem +1;
        bdElem(kElem,1) = ielem;
    end
end
%triplot(T, X1, Y1);
%hold on;
disp('finished getting elements at boundary');
%---------------------------------------------------------------------
% get co-ordinates at element centres
%---------------------------------------------------------------------
nElems = length(bdElem);
FV_OBC.nElems  = nElems;
FV_OBC.nElemID = bdElem;
% get element centres
IC = incenter(TR,bdElem);
lonc = IC(:,1)';        % arrange in one row
latc = IC(:,2)';        % arrange in one row
FV_OBC.lonc = lonc;
FV_OBC.latc = latc;
FV_OBC.xc = lonc;   % temp solution
FV_OBC.yc = latc;   % temp solution
% get element nodes & arrange in required format
nv = zeros(3,nElems);
for i=1:nElems
    ielem = bdElem(i);
    nv(1,i) = FV_Mesh.tri(ielem,1);
    nv(2,i) = FV_Mesh.tri(ielem,2);
    nv(3,i) = FV_Mesh.tri(ielem,3);
end
FV_OBC.nv = nv;
FV_OBC.tri=nv;
disp('finished getting co-ordinates of element centres at boundary');
%get number of layers
FV_OBC.nsiglay=nsiglay;
FV_OBC.nsiglev=nsiglay+1;
inc = 1/real(nsiglay);
siglev = 0:-inc:-1;
siglay = nan(1, nsiglay);
for i=1:nsiglay
    siglay(i) = mean(siglev(i:i+1));
end
FV_OBC.siglay=siglay;
FV_OBC.siglev=siglev;
%---------------------------------------------------------
% Interpolate AMM data onto mesh
%---------------------------------------------------------
%call get_AMM to read in elevation, UV and T/S (via call to another
%function) data and store in FV_OBC
FV_OBC = get_AMM_ZUV(FV_OBC,StartDate,EndDate,AMMDir);
%plot output
% plot boundary values ??
if(0)
    figure(1);
    hold on;
    for j = 1:100 % time
        clf;
        scatter(FV_OBC.lon,FV_OBC.lat,5,Hs(j,:)');
        pause;%(3);
    end
end
%%
if(1)    %Due to a shock at the beginning when introducing the nesting from a hot
    %start (obtained at the end of a cold start) the first x hours of velocity will be
    %gradually built up.  Also ramp up temperature and salinity
    %when running from cold you should have a constant temperature and salinity
    timeinterval=((FV_OBC.time(2)-FV_OBC.time(1))*24.);
    numiters=ceil((smoothtime/timeinterval)+1);
    shiftiter=-1*ceil(shift.*24/timeinterval);
%smooth introduction of water level and speed
FV_OBC.daUvel(FV_OBC.daUvel==0.00)=0.00001;
FV_OBC.daVvel(FV_OBC.daVvel==0.00)=0.00001;
FV_OBC.u(FV_OBC.u==0.00)=0.00001;
FV_OBC.v(FV_OBC.v==0.00)=0.00001;
FV_OBC.surfaceElevation(FV_OBC.surfaceElevation==0.00)=0.00001;
    for ielem=1:FV_OBC.nElems
        interpua=(speed_init:((FV_OBC.daUvel(ielem,numiters)-speed_init)/(numiters-1)):FV_OBC.daUvel(ielem,numiters));
        interpva=(speed_init:((FV_OBC.daVvel(ielem,numiters)-speed_init)/(numiters-1)):FV_OBC.daVvel(ielem,numiters));
        FV_OBC.daUvel(ielem,1+shiftiter:numiters+shiftiter)=interpua;
        FV_OBC.daVvel(ielem,1+shiftiter:numiters+shiftiter)=interpva;
        for ilay=1:FV_OBC.nsiglay
            interpu=(speed_init:((FV_OBC.u(ielem,ilay,numiters)-speed_init)/(numiters-1)):FV_OBC.u(ielem,ilay,numiters));
            interpv=(speed_init:((FV_OBC.v(ielem,ilay,numiters)-speed_init)/(numiters-1)):FV_OBC.v(ielem,ilay,numiters));
            FV_OBC.u(ielem,ilay,1+shiftiter:numiters+shiftiter)=interpu;
            FV_OBC.v(ielem,ilay,1+shiftiter:numiters+shiftiter)=interpv;
        end
    end
    for inode=1:FV_OBC.nVerts
        interpsurfaceElevation=(surfaceElevation_init:((FV_OBC.surfaceElevation(inode,numiters)-surfaceElevation_init)/(numiters-1)):FV_OBC.surfaceElevation(inode,numiters));
        FV_OBC.surfaceElevation(inode,1+shiftiter:numiters+shiftiter)=interpsurfaceElevation;
        for ilay=1:FV_OBC.nsiglay
            interpsalinity=(salinity_init:((FV_OBC.salinity(inode,ilay,numiters)-salinity_init)/(numiters-1)):FV_OBC.salinity(inode,ilay,numiters));
            interptemperature=(temp_init:((FV_OBC.temperature(inode,ilay,numiters)-temp_init)/(numiters-1)):FV_OBC.temperature(inode,ilay,numiters));
            FV_OBC.salinity(inode,ilay,1+shiftiter:numiters+shiftiter)=interpsalinity;
            FV_OBC.temperature(inode,ilay,1+shiftiter:numiters+shiftiter)=interptemperature;
        end
    end
end
figure(150);
plot(squeeze(FV_OBC.surfaceElevation(23,:)));
figure(151);
plot(squeeze(FV_OBC.salinity(23,1,:)));
figure(152);
hold on;
plot(squeeze(FV_OBC.daUvel(23,:)),'k-');
plot(squeeze(FV_OBC.daVvel(23,:)),'r-');
%%
%weighting for type 3 nesting
OBCnodes= get_HD_OBC(bdyobcFile);
nodes_on_bdy=OBCnodes.nnodesID;
[I]=ismember(FV_OBC.nnodesID,nodes_on_bdy); % nodes on boundary with weight 1
[Jval, J]=setdiff(FV_OBC.nnodesID,nodes_on_bdy); %need an array of nodes not on bdy for weight 2
weight_node_val=ones(FV_OBC.nVerts,1);
weight_elem_val=weight_elem_val.*ones(FV_OBC.nElems,1);% element weight
weight_node_val(I)=weight_node_val(I).*weight_node1;
weight_node_val(J)=weight_node_val(J).*weight_node2;
%now repeat matrices for time dimension
FV_OBC.weight_node_val=repmat(weight_node_val,1,numel(FV_OBC.time));
FV_OBC.weight_elem_val=repmat(weight_elem_val,1,numel(FV_OBC.time));
FV_OBC.NEST_TYPE=NEST_TYPE;
% now output boundary data to the FVCOM netcdf format
write_nesting_bdy_file(FV_OBC, FV_OBC.time-datenum(1858,11,17,0,0,0)+shift, HDFile, MyTitle);
disp('net cdf wave file written');