Description of example2
Home > fvcom_prepro > example2.m
example2
PURPOSE
example demonstrating reading in an FVCOM mesh and smoothing the bathymetry
SYNOPSIS
This is a script file.
DESCRIPTION
 example demonstrating reading in an FVCOM mesh and smoothing the bathymetry
 function example
 DESCRIPTION:
    Read in FVCOM mesh
    Read in FVCOM bathymetry
    Smooth bathymetry
    Dump new bathymetry
 INPUT
 OUTPUT:
    Smoothed Bathymetry File
 EXAMPLE USAGE
    example2
 Author(s):
    Geoff Cowles (University of Massachusetts Dartmouth)
 Revision history
==============================================================================
CROSS-REFERENCE INFORMATION
This function calls:
plot_field Plot the mesh, user defined field, open boundary nodes, and river points
read_fvcom_bath Read fvcom bathymetry file
read_fvcom_mesh Read fvcom mesh file into Matlab mesh object
setup_metrics Setup metrics for mesh object Mesh
smoothfield Smooth a vertex-based field using averages
write_FVCOM_bath Write bathymetry to FVCOM format bathymetry file
This function is called by:
SOURCE CODE
% example demonstrating reading in an FVCOM mesh and smoothing the bathymetry
%
% function example
%
% DESCRIPTION:
%    Read in FVCOM mesh
%    Read in FVCOM bathymetry
%    Smooth bathymetry
%    Dump new bathymetry
%
% INPUT
%
% OUTPUT:
%    Smoothed Bathymetry File
%
% EXAMPLE USAGE
%    example2
%
% Author(s):
%    Geoff Cowles (University of Massachusetts Dartmouth)
%
% Revision history
%
%==============================================================================
clear all; close all;
% read the Mesh from an FVCOM grid file
Mobj = read_fvcom_mesh('skg4.3_grd.dat');
% read the bathymetry from an FVCOM grid file
Mobj.h = read_fvcom_bath('skg4.3_dep.dat');  Mobj.have_bath = true;
% smooth bathymetry with 4 iterations of explicit smoother
plot_field(Mobj,Mobj.h,'title','original bathymetry')
Mobj = setup_metrics(Mobj);
[Mobj.h] = smoothfield(Mobj.h,Mobj,0.5,4);
plot_field(Mobj,Mobj.h,'title','smoothed bathymetry');
% dump bathymetry
write_FVCOM_bath(Mobj,'skg4.3_dep_smoothed.dat')