Description of make_blank_mesh
Home > fvcom_prepro > make_blank_mesh.m
make_blank_mesh
PURPOSE
Make a blank mesh object with default params
SYNOPSIS
function [Mobj] = make_blank_mesh
DESCRIPTION
 Make a blank mesh object with default params
 [Mobj] = function make_blank_mesh
 DESCRIPTION:
    Make a blank Matlab mesh object
 INPUT:
 OUTPUT:
    Mobj = matlab structure containing default
 EXAMPLE USAGE
    Mobj = make_blank_mesh()
 Author(s):
    Geoff Cowles (University of Massachusetts Dartmouth)
    Pierre Cazenave (Plymouth Marine Laboratory)
 Revision history
    2015-05-20 Add new boolean flag for rivers.
==============================================================================
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gen_semistructured_mesh Generate a semistructured mesh
gen_unstructured_mesh function gen_unstructured_mesh(lx,ly,res,cornermod)
read_gmsh_mesh Read gmsh mesh files (version 2.2) into MATLAB mesh object.
read_grid_mesh Read .grid mesh files into Matlab mesh object
read_sms_mesh Read sms mesh files into Matlab mesh object.
SOURCE CODE
function [Mobj] = make_blank_mesh
% Make a blank mesh object with default params
%
% [Mobj] = function make_blank_mesh
%
% DESCRIPTION:
%    Make a blank Matlab mesh object
%
% INPUT:
%
% OUTPUT:
%    Mobj = matlab structure containing default
%
% EXAMPLE USAGE
%    Mobj = make_blank_mesh()
%
% Author(s):
%    Geoff Cowles (University of Massachusetts Dartmouth)
%    Pierre Cazenave (Plymouth Marine Laboratory)
%
% Revision history
%    2015-05-20 Add new boolean flag for rivers.
%
%==============================================================================
global ftbverbose
subname = 'make_blank_mesh';
if(ftbverbose)
  fprintf('\n')
  fprintf(['begin : ' subname '\n'])
end;
%------------------------------------------------------------------------------
% Set defaults
%------------------------------------------------------------------------------
% dimensions
Mobj.nVerts  = 0;
Mobj.nElems  = 0;
Mobj.nRivers = 0;
Mobj.nObs    = 0;
Mobj.nSponge = 0;
Mobj.riv_nodes = zeros(50,10);
Mobj.obc_nodes = zeros(10,500);
Mobj.sponge_nodes = zeros(10,500);
% flags
Mobj.nativeCoords = 'cartesian';
Mobj.have_lonlat  = false;
Mobj.have_cor     = false;
Mobj.have_xy      = false;
Mobj.have_bath    = false;
Mobj.have_mets    = false;
Mobj.have_rivers  = false;
if(ftbverbose)
  fprintf(['end   : ' subname '\n'])
end;