Description of nodes2elems
Home > fvcom_prepro > nodes2elems.m
nodes2elems
PURPOSE
Transfer a field from vertices to elements
SYNOPSIS
function fieldout = nodes2elems(fieldin,Mobj)
DESCRIPTION
 Transfer a field from vertices to elements
 function fieldout = nodes2elems(fieldin, Mobj)
 DESCRIPTION:
    Transfer a field from vertices (nodes) to elements
 INPUT
    Mobj         = Matlab mesh object
    fieldin      = vertex-based field
 OUTPUT:
    fieldout = element-based field
 EXAMPLE USAGE
    f = smoothfield(fv, Mobj)
 Author(s):
    Geoff Cowles (University of Massachusetts Dartmouth)
    Pierre Cazenave (Plymouth Marine Laboratory)
 Revision history
   2014-03-10 Made the calculation array-based instead of loop-based
   (increases performance).
==========================================================================
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
get_POLCOMS_meanflow Read mean flow from the PML POLCOMS-ERSEM NetCDF AMM model output files
hybrid_coordinate Create a hybrid vertical coordinates file.
read_sigma Read an FVCOM sigma layers file and output z values into Mobj.
read_sms_mesh Read sms mesh files into Matlab mesh object.
write_FVCOM_forcing Write data out to FVCOM netCDF forcing file.
write_FVCOM_heating Write data out to FVCOM NetCDF heating file (for HEATING_CALCULATED).
SOURCE CODE
function fieldout = nodes2elems(fieldin,Mobj)
% Transfer a field from vertices to elements
%
% function fieldout = nodes2elems(fieldin, Mobj)
%
% DESCRIPTION:
%    Transfer a field from vertices (nodes) to elements
%
% INPUT
%    Mobj         = Matlab mesh object
%    fieldin      = vertex-based field
%
% OUTPUT:
%    fieldout = element-based field
%
% EXAMPLE USAGE
%    f = smoothfield(fv, Mobj)
%
% Author(s):
%    Geoff Cowles (University of Massachusetts Dartmouth)
%    Pierre Cazenave (Plymouth Marine Laboratory)
%
% Revision history
%   2014-03-10 Made the calculation array-based instead of loop-based
%   (increases performance).
%
%==========================================================================
subname = 'nodes2elems';
global ftbverbose
if ftbverbose
    fprintf('\nbegin : %s \n', subname)
end
%--------------------------------------------------------------------------
% Parse input
%--------------------------------------------------------------------------
if exist('fieldin', 'var') ~= 1 || exist('Mobj', 'var') ~= 1
    error('arguments to nodes2elems are missing')
end
if length(fieldin) ~= Mobj.nVerts
    error('field size in nodes2elems is not the same as number of nodes in Mesh')
end
%--------------------------------------------------------------------------
% Tranfser
%--------------------------------------------------------------------------
fieldout = mean(fieldin(Mobj.tri), 2);
if ftbverbose
    fprintf('end   : %s \n', subname)
end