function [fmt, nml] = make_default_nml(conf)
% Generate a model namelist with the default values from FVCOM.
%
% [fmt, nml] = make_default_nml(conf)
%
% INPUTS
%    conf - struct with the following fields
%        version: FVCOM version (e.g. 'ver4.0')
%        casename: model casename
%
% OUTPUT
%    fmt - struct with the number format for each field when writing 
%          the namelist.
%    nml - struct with fields for each namelist section.
%
% Revision history
%    2017-01-12 First version.
%
% Author(s)
%    Ricardo Torres (Plymouth Marine Laboratory)
%    Pierre Cazenave (Plymouth Marine Laboratory)
        
nml.NML_CASE = [];
nml.NML_CASE.CASE_TITLE=['FVCOM ', conf.version, ' code'] ;
nml.NML_CASE.TIMEZONE='UTC';
nml.NML_CASE.DATE_FORMAT='YMD';
nml.NML_CASE.DATE_REFERENCE='default';
nml.NML_CASE.START_DATE='2006-02-01 00:00:00';
nml.NML_CASE.END_DATE='2006-03-01 00:00:00';

%%
nml.NML_STARTUP = [];
nml.NML_STARTUP.STARTUP_TYPE      = 'coldstart';
nml.NML_STARTUP.STARTUP_FILE      = [conf.casename, '_restart.nc'];
nml.NML_STARTUP.STARTUP_UV_TYPE   = 'default';
nml.NML_STARTUP.STARTUP_TURB_TYPE = 'default';
nml.NML_STARTUP.STARTUP_TS_TYPE   = 'constant';
nml.NML_STARTUP.STARTUP_T_VALS    = 18.5;
fmt.NML_STARTUP.STARTUP_T_VALS.format    = '%5.2f';
nml.NML_STARTUP.STARTUP_S_VALS    = 35.6;
fmt.NML_STARTUP.STARTUP_S_VALS.format    = '%5.2f';
nml.NML_STARTUP.STARTUP_U_VALS    = 0.0E+0;
fmt.NML_STARTUP.STARTUP_U_VALS.format    = '%5.2f';
nml.NML_STARTUP.STARTUP_V_VALS    = 0.0E+0;
fmt.NML_STARTUP.STARTUP_V_VALS.format    = '%5.2f';
nml.NML_STARTUP.STARTUP_DMAX      =  -5.0;
fmt.NML_STARTUP.STARTUP_DMAX.format      =  '%5.2f';
%/
%%
nml.NML_IO = [];
nml.NML_IO.INPUT_DIR       =  './input';
nml.NML_IO.OUTPUT_DIR      =  './output';
nml.NML_IO.IREPORT         =  10000;
fmt.NML_IO.IREPORT.format         =  '%u';
nml.NML_IO.VISIT_ALL_VARS  = 'F';
nml.NML_IO.WAIT_FOR_VISIT  = 'F';
nml.NML_IO.USE_MPI_IO_MODE = 'F';
%/
%%
nml.NML_INTEGRATION = [];
nml.NML_INTEGRATION.EXTSTEP_SECONDS =  0.2 ;
fmt.NML_INTEGRATION.EXTSTEP_SECONDS.format =  '%6.3f' ;
nml.NML_INTEGRATION.ISPLIT          =  10 ;
fmt.NML_INTEGRATION.ISPLIT.format          =  '%u' ;
nml.NML_INTEGRATION.IRAMP           =  864000; %! 24 hours with dt=0.2
fmt.NML_INTEGRATION.IRAMP.format           =  '%u' ; %! 24 hours with dt=0.2
nml.NML_INTEGRATION.MIN_DEPTH       =  0.2;
fmt.NML_INTEGRATION.MIN_DEPTH.format       =  '%5.2f';
nml.NML_INTEGRATION.STATIC_SSH_ADJ  =  0.0;
fmt.NML_INTEGRATION.STATIC_SSH_ADJ.format  =  '%5.2f';
%/
%%
nml.NML_RESTART = [];
nml.NML_RESTART.RST_ON  = 'T';
nml.NML_RESTART.RST_FIRST_OUT      = '2046-03-01 00:00:00';%
nml.NML_RESTART.RST_OUT_INTERVAL   = 'seconds = 86400.';%
nml.NML_RESTART.RST_OUTPUT_STACK   =           0;
fmt.NML_RESTART.RST_OUTPUT_STACK.format   =           '%u';
%/
%%
nml.NML_NETCDF = [];
nml.NML_NETCDF.NC_ON   = 'T';
nml.NML_NETCDF.NC_FIRST_OUT    = '2046-02-01 00:00:00';%
nml.NML_NETCDF.NC_OUT_INTERVAL =  'seconds= 3600.';%
nml.NML_NETCDF.NC_OUTPUT_STACK =  0;%
fmt.NML_NETCDF.NC_OUTPUT_STACK.format =  '%u';%
nml.NML_NETCDF.NC_SUBDOMAIN_FILES      = 'FVCOM' ;%
nml.NML_NETCDF.NC_GRID_METRICS = 'T';
nml.NML_NETCDF.NC_FILE_DATE    = 'T';
nml.NML_NETCDF.NC_VELOCITY     = 'F';
switch conf.version
    case 'fvcom-offline'
        nml.NML_NETCDF.NC_OFFLINE      = 'T';
    case 'ver3.2.1'
    case 'ver3.1.6'
    case 'ver4.0'
        nml.NML_NETCDF.NC_OFFLINE      = 'T';
end
nml.NML_NETCDF.NC_SALT_TEMP    = 'F';
nml.NML_NETCDF.NC_TURBULENCE   = 'F';
nml.NML_NETCDF.NC_AVERAGE_VEL  = 'T';
nml.NML_NETCDF.NC_VERTICAL_VEL = 'F';
nml.NML_NETCDF.NC_WIND_VEL     = 'F';
nml.NML_NETCDF.NC_WIND_STRESS  = 'F';
nml.NML_NETCDF.NC_EVAP_PRECIP  = 'F';
nml.NML_NETCDF.NC_SURFACE_HEAT = 'F';
nml.NML_NETCDF.NC_GROUNDWATER  = 'F';
nml.NML_NETCDF.NC_BIO          = 'F';
nml.NML_NETCDF.NC_WQM          = 'F';
nml.NML_NETCDF.NC_VORTICITY    = 'F';
switch conf.version
    case 'ver4.0'
    case 'ver4.0-ersem'
        nml.NML_NETCDF.NC_FABM      = 'T';
end%/
%%
nml.NML_NETCDF_AV = [];
nml.NML_NETCDF_AV.NCAV_ON = 'F';
nml.NML_NETCDF_AV.NCAV_FIRST_OUT  = '2046-02-01 00:00:00';%
nml.NML_NETCDF_AV.NCAV_OUT_INTERVAL       =  'seconds= 3600.';%
nml.NML_NETCDF_AV.NCAV_OUTPUT_STACK       =           0;%
fmt.NML_NETCDF_AV.NCAV_OUTPUT_STACK.format       =           '%u';%
nml.NML_NETCDF_AV.NCAV_GRID_METRICS       = 'F';
nml.NML_NETCDF_AV.NCAV_FILE_DATE  = 'T';
nml.NML_NETCDF_AV.NCAV_VELOCITY   = 'F';
switch conf.version
    case 'fvcom-ersem'
        nml.NML_NETCDF_AV.NCAV_OFFLINE      = 'F';
    case 'ver3.2.1'
    case 'ver3.1.6'
end
nml.NML_NETCDF_AV.NCAV_SALT_TEMP  = 'T';
nml.NML_NETCDF_AV.NCAV_TURBULENCE = 'F';
nml.NML_NETCDF_AV.NCAV_AVERAGE_VEL        = 'F';
nml.NML_NETCDF_AV.NCAV_VERTICAL_VEL       = 'F';
nml.NML_NETCDF_AV.NCAV_WIND_VEL   = 'F';
nml.NML_NETCDF_AV.NCAV_WIND_STRESS        = 'F';
nml.NML_NETCDF_AV.NCAV_EVAP_PRECIP        = 'F';
nml.NML_NETCDF_AV.NCAV_SURFACE_HEAT       = 'F';
nml.NML_NETCDF_AV.NCAV_GROUNDWATER        = 'F';
nml.NML_NETCDF_AV.NCAV_BIO        = 'F';
nml.NML_NETCDF_AV.NCAV_WQM        = 'F';
nml.NML_NETCDF_AV.NCAV_VORTICITY  = 'F';
switch conf.version
    case 'ver4.0'
    case 'ver4.0-ersem'
        nml.NML_NETCDF_AV.NCAV_FABM      = 'T';
end%/
%/
%%
nml.NML_SURFACE_FORCING = [];
nml.NML_SURFACE_FORCING.WIND_ON 			= 'T';
nml.NML_SURFACE_FORCING.WIND_TYPE       		= 'speed';%
nml.NML_SURFACE_FORCING.WIND_FILE      		= [conf.casename '_wnd.nc'];%
nml.NML_SURFACE_FORCING.WIND_KIND      		= 'variable';%
nml.NML_SURFACE_FORCING.WIND_X 			=  5.0000000E+00;%
fmt.NML_SURFACE_FORCING.WIND_X.format 			=  '%5.2f';%
nml.NML_SURFACE_FORCING.WIND_Y 			=  5.0000000E+00;%
fmt.NML_SURFACE_FORCING.WIND_Y.format 			=  '%5.2f';%
nml.NML_SURFACE_FORCING.HEATING_ON     		= 'T';
nml.NML_SURFACE_FORCING.HEATING_TYPE   		= 'flux';%
nml.NML_SURFACE_FORCING.HEATING_KIND   		= 'variable' ;%
nml.NML_SURFACE_FORCING.HEATING_FILE    		= [conf.casename '_wnd.nc'];%
nml.NML_SURFACE_FORCING.HEATING_LONGWAVE_LENGTHSCALE   =  1.4;%
fmt.NML_SURFACE_FORCING.HEATING_LONGWAVE_LENGTHSCALE.format   =  '%5.2f';%
nml.NML_SURFACE_FORCING.HEATING_LONGWAVE_PERCTAGE      =  0.78;%
fmt.NML_SURFACE_FORCING.HEATING_LONGWAVE_PERCTAGE.format      =  '%5.2f';%
nml.NML_SURFACE_FORCING.HEATING_SHORTWAVE_LENGTHSCALE  =  6.3;%
fmt.NML_SURFACE_FORCING.HEATING_SHORTWAVE_LENGTHSCALE.format  =  '%5.2f';%
nml.NML_SURFACE_FORCING.HEATING_RADIATION     		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.HEATING_RADIATION.format     		=  '%6.2f';%
nml.NML_SURFACE_FORCING.HEATING_NETFLUX		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.HEATING_NETFLUX.format		=  '%6.2f';%
nml.NML_SURFACE_FORCING.PRECIPITATION_ON    		= 'T';
nml.NML_SURFACE_FORCING.PRECIPITATION_KIND  		= 'variable';%
nml.NML_SURFACE_FORCING.PRECIPITATION_FILE   		= [conf.casename '_wnd.nc'];%
nml.NML_SURFACE_FORCING.PRECIPITATION_PRC    		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.PRECIPITATION_PRC.format    		=  '%6.2f';%
nml.NML_SURFACE_FORCING.PRECIPITATION_EVP    		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.PRECIPITATION_EVP.format    		=  '%6.2f';%
nml.NML_SURFACE_FORCING.AIRPRESSURE_ON 		= 'T';
nml.NML_SURFACE_FORCING.AIRPRESSURE_KIND    		= 'variable';%
nml.NML_SURFACE_FORCING.AIRPRESSURE_FILE    		= [conf.casename '_wnd.nc'];%
nml.NML_SURFACE_FORCING.AIRPRESSURE_VALUE       	=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.AIRPRESSURE_VALUE.format       	=  '%10.2f';%
nml.NML_SURFACE_FORCING.WAVE_ON 			= 'F';
nml.NML_SURFACE_FORCING.WAVE_FILE       		= [conf.casename '_wav.nc'];%
nml.NML_SURFACE_FORCING.WAVE_KIND       		= 'constant';%
nml.NML_SURFACE_FORCING.WAVE_HEIGHT     		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.WAVE_HEIGHT.format     		=  '%5.2f';%
nml.NML_SURFACE_FORCING.WAVE_LENGTH     		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.WAVE_LENGTH.format     		=  '%5.2f';%
nml.NML_SURFACE_FORCING.WAVE_DIRECTION  		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.WAVE_DIRECTION.format  		=  '%5.2f';%
nml.NML_SURFACE_FORCING.WAVE_PERIOD     		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.WAVE_PERIOD.format     		=  '%5.2f';%
nml.NML_SURFACE_FORCING.WAVE_PER_BOT    		=  0.0000000E+00;%
fmt.NML_SURFACE_FORCING.WAVE_PER_BOT.format    		=  '%5.2f';%
nml.NML_SURFACE_FORCING.WAVE_UB_BOT     		=  0.0000000E+00;
fmt.NML_SURFACE_FORCING.WAVE_UB_BOT.format     		=  '%5.2f';
%/
%%
nml.NML_HEATING_CALCULATED = [];
nml.NML_HEATING_CALCULATED.HEATING_CALCULATE_ON    = 'F';
nml.NML_HEATING_CALCULATED.HEATING_CALCULATE_TYPE  = 'flux'     ;%
nml.NML_HEATING_CALCULATED.HEATING_CALCULATE_FILE  = [conf.casename '_wnd.nc'];   %
nml.NML_HEATING_CALCULATED.HEATING_CALCULATE_KIND  = 'variable'                     ;%
nml.NML_HEATING_CALCULATED.ZUU     		 =   10.00000000000000     ;%
fmt.NML_HEATING_CALCULATED.ZUU.format     		 =   '%5.2f'     ;%
nml.NML_HEATING_CALCULATED.ZTT    		 =   10.00000000000000     ;%
fmt.NML_HEATING_CALCULATED.ZTT.format    		 =   '%5.2f'     ;%
nml.NML_HEATING_CALCULATED.ZQQ     		 =   10.00000000000000     ;%
fmt.NML_HEATING_CALCULATED.ZQQ.format     		 =   '%5.2f'     ;%
nml.NML_HEATING_CALCULATED.AIR_TEMPERATURE 	 =  0.000000000000000E+000;%
fmt.NML_HEATING_CALCULATED.AIR_TEMPERATURE.format 	 =  '%5.2f';%
nml.NML_HEATING_CALCULATED.RELATIVE_HUMIDITY       =  0.000000000000000E+000;%
fmt.NML_HEATING_CALCULATED.RELATIVE_HUMIDITY.format       =  '%5.2f';%
nml.NML_HEATING_CALCULATED.SURFACE_PRESSURE        =  0.000000000000000E+000;%
fmt.NML_HEATING_CALCULATED.SURFACE_PRESSURE.format        =  '%5.2f';%
nml.NML_HEATING_CALCULATED.LONGWAVE_RADIATION      =  0.000000000000000E+000;%
fmt.NML_HEATING_CALCULATED.LONGWAVE_RADIATION.format      =  '%6.2f';%
nml.NML_HEATING_CALCULATED.SHORTWAVE_RADIATION     =  0.000000000000000E+000;
fmt.NML_HEATING_CALCULATED.SHORTWAVE_RADIATION.format     =  '%6.2f';
nml.NML_HEATING_CALCULATED.HEATING_LONGWAVE_PERCTAGE_IN_HEATFLUX     = 0.78;%
fmt.NML_HEATING_CALCULATED.HEATING_LONGWAVE_PERCTAGE_IN_HEATFLUX.format     = '%5.2f';%
nml.NML_HEATING_CALCULATED.HEATING_LONGWAVE_LENGTHSCALE_IN_HEATFLUX  = 1.4;%
fmt.NML_HEATING_CALCULATED.HEATING_LONGWAVE_LENGTHSCALE_IN_HEATFLUX.format  = '%5.2f';%
nml.NML_HEATING_CALCULATED.HEATING_SHORTWAVE_LENGTHSCALE_IN_HEATFLUX = 6.3;
fmt.NML_HEATING_CALCULATED.HEATING_SHORTWAVE_LENGTHSCALE_IN_HEATFLUX.format = '%5.2f';
%/
%%
nml.NML_PHYSICS = [];
nml.NML_PHYSICS.HORIZONTAL_MIXING_TYPE          = 'closure';
nml.NML_PHYSICS.HORIZONTAL_MIXING_KIND          = 'constant';
nml.NML_PHYSICS.HORIZONTAL_MIXING_COEFFICIENT   = 2.0e-1;
fmt.NML_PHYSICS.HORIZONTAL_MIXING_COEFFICIENT.format   = '%e';
nml.NML_PHYSICS.HORIZONTAL_PRANDTL_NUMBER       = 1.0;
fmt.NML_PHYSICS.HORIZONTAL_PRANDTL_NUMBER.format       = '%5.2f';
nml.NML_PHYSICS.VERTICAL_MIXING_TYPE            = 'closure';
nml.NML_PHYSICS.VERTICAL_MIXING_COEFFICIENT     = 1.0E-5;%
fmt.NML_PHYSICS.VERTICAL_MIXING_COEFFICIENT.format     = '%e';%
nml.NML_PHYSICS.VERTICAL_PRANDTL_NUMBER         = 1.0;
fmt.NML_PHYSICS.VERTICAL_PRANDTL_NUMBER.format         = '%5.2f';
nml.NML_PHYSICS.BOTTOM_ROUGHNESS_MINIMUM        =  0.0025;
fmt.NML_PHYSICS.BOTTOM_ROUGHNESS_MINIMUM.format        =  '%e';
nml.NML_PHYSICS.BOTTOM_ROUGHNESS_LENGTHSCALE    =  -1.0;
fmt.NML_PHYSICS.BOTTOM_ROUGHNESS_LENGTHSCALE.format    =  '%5.2f';
nml.NML_PHYSICS.BOTTOM_ROUGHNESS_KIND           = 'static';
nml.NML_PHYSICS.BOTTOM_ROUGHNESS_TYPE           = 'orig';
nml.NML_PHYSICS.BOTTOM_ROUGHNESS_FILE           = [conf.casename '_z0=0.005.nc'];
nml.NML_PHYSICS.CONVECTIVE_OVERTURNING          = 'F';
nml.NML_PHYSICS.SCALAR_POSITIVITY_CONTROL       = 'T';
nml.NML_PHYSICS.BAROTROPIC                      = 'F';
nml.NML_PHYSICS.BAROCLINIC_PRESSURE_GRADIENT    = 'sigma levels';
nml.NML_PHYSICS.SEA_WATER_DENSITY_FUNCTION      = 'dens2';
nml.NML_PHYSICS.RECALCULATE_RHO_MEAN            = 'F';
nml.NML_PHYSICS.INTERVAL_RHO_MEAN               = 'days=1.0';% ! 'seconds=1800.';%
nml.NML_PHYSICS.TEMPERATURE_ACTIVE              = 'T';
nml.NML_PHYSICS.SALINITY_ACTIVE                 = 'T';
nml.NML_PHYSICS.SURFACE_WAVE_MIXING             = 'F';
nml.NML_PHYSICS.WETTING_DRYING_ON               = 'T';
nml.NML_PHYSICS.NOFLUX_BOT_CONDITION          = 'T';
nml.NML_PHYSICS.ADCOR_ON        = 'T';
nml.NML_PHYSICS.EQUATOR_BETA_PLANE      = 'F';
nml.NML_PHYSICS.BACKWARD_ADVECTION      = 'T';
nml.NML_PHYSICS.BACKWARD_STEP   =          1;%! it can only be 1 or 2
fmt.NML_PHYSICS.BACKWARD_STEP.format    =  '%u';
%%/
%%
nml.NML_RIVER_TYPE = [];
nml.NML_RIVER_TYPE.RIVER_NUMBER    =           0;%
fmt.NML_RIVER_TYPE.RIVER_NUMBER.format    =           '%u';%
nml.NML_RIVER_TYPE.RIVER_KIND      =         'variable';
nml.NML_RIVER_TYPE.RIVER_TS_SETTING        = 'calculated';
nml.NML_RIVER_TYPE.RIVER_INFLOW_LOCATION   = 'node';
nml.NML_RIVER_TYPE.RIVER_INFO_FILE       = [conf.casename '_riv_ersem.nml'];
%/
%%
nml.NML_OPEN_BOUNDARY_CONTROL = [];
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_ON                      = 'T';
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_NODE_LIST_FILE          = [conf.casename '_obc.dat'];
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_ELEVATION_FORCING_ON    = 'T';
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_ELEVATION_FILE          = [conf.casename '_elevtide.nc'];
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_TS_TYPE                 = 3;
fmt.NML_OPEN_BOUNDARY_CONTROL.OBC_TS_TYPE.format                 = '%u';
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_TEMP_NUDGING            = 'T';
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_TEMP_FILE               = [conf.casename '_tsobc.nc'];
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_TEMP_NUDGING_TIMESCALE  =  0.00005;% !0.0014;%
fmt.NML_OPEN_BOUNDARY_CONTROL.OBC_TEMP_NUDGING_TIMESCALE.format  =  '%15.10f';% !0.0014;%
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_SALT_NUDGING            = 'T';
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_SALT_FILE               = [conf.casename '_tsobc.nc'];
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_SALT_NUDGING_TIMESCALE  =  0.00005;% !0.0014;%
fmt.NML_OPEN_BOUNDARY_CONTROL.OBC_SALT_NUDGING_TIMESCALE.format  =  '%15.10f';% !0.0014;%   switch conf.version
switch conf.version
    case 'ver4.0'
    case 'ver4.0-ersem'
        nml.NML_OPEN_BOUNDARY_CONTROL.OBC_FABM_NUDGING            = 'F';
        nml.NML_OPEN_BOUNDARY_CONTROL.OBC_FABM_FILE               = [conf.casename '_ERSEMobc.nc'];
        nml.NML_OPEN_BOUNDARY_CONTROL.OBC_FABM_NUDGING_TIMESCALE  =  0.00005;% !0.0014;%
        fmt.NML_OPEN_BOUNDARY_CONTROL.OBC_FABM_NUDGING_TIMESCALE.format  =  '%15.10f';% !0.0014;%   switch conf.version
end%/

nml.NML_OPEN_BOUNDARY_CONTROL.OBC_MEANFLOW                = 'F';
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_MEANFLOW_FILE           = [conf.casename '_meanflow.nc'];
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_TIDEOUT_INITIAL         = 1;%
fmt.NML_OPEN_BOUNDARY_CONTROL.OBC_TIDEOUT_INITIAL.format         = '%u';%
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_TIDEOUT_INTERVAL        = 900;%   ! ELO_TM%TIMES(I)=(TTIME+DELTT*DTI) ! was 720! (5s*720)=3600s
fmt.NML_OPEN_BOUNDARY_CONTROL.OBC_TIDEOUT_INTERVAL.format        = '%u';%   ! ELO_TM%TIMES(I)=(TTIME+DELTT*DTI) ! was 720! (5s*720)=3600s
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_LONGSHORE_FLOW_ON       = 'F';
nml.NML_OPEN_BOUNDARY_CONTROL.OBC_LONGSHORE_FLOW_FILE     = [conf.casename '_lsf.dat'];
%/
%%

nml.NML_GRID_COORDINATES = [];
nml.NML_GRID_COORDINATES.GRID_FILE       = [conf.casename '_grd.dat'];
nml.NML_GRID_COORDINATES.GRID_FILE_UNITS = 'meters';
nml.NML_GRID_COORDINATES.PROJECTION_REFERENCE  = 'proj=utm +ellps=WGS84 +zone=29';
nml.NML_GRID_COORDINATES.SIGMA_LEVELS_FILE     = 'sigma.dat';
nml.NML_GRID_COORDINATES.DEPTH_FILE      = [conf.casename '_dep.dat'];
nml.NML_GRID_COORDINATES.CORIOLIS_FILE   = [conf.casename '_cor.dat'];
nml.NML_GRID_COORDINATES.SPONGE_FILE     = [conf.casename '_spg.dat'];
%/
%%
nml.NML_GROUNDWATER = [];
nml.NML_GROUNDWATER.GROUNDWATER_ON      = 'F';
nml.NML_GROUNDWATER.GROUNDWATER_TEMP_ON = 'F';
nml.NML_GROUNDWATER.GROUNDWATER_SALT_ON = 'F';
nml.NML_GROUNDWATER.GROUNDWATER_KIND    = 'none';%
nml.NML_GROUNDWATER.GROUNDWATER_FILE    = 'none';%
nml.NML_GROUNDWATER.GROUNDWATER_FLOW    = 0.0;%
fmt.NML_GROUNDWATER.GROUNDWATER_FLOW.format    = '%10.6f';%
nml.NML_GROUNDWATER.GROUNDWATER_TEMP    = 0.0000000E+00;%
fmt.NML_GROUNDWATER.GROUNDWATER_TEMP.format    = '%10.6f';%
nml.NML_GROUNDWATER.GROUNDWATER_SALT    = 0.0000000E+00;
fmt.NML_GROUNDWATER.GROUNDWATER_SALT.format    = '%10.6f';
%/
%%
nml.NML_LAG = [];
nml.NML_LAG.LAG_PARTICLES_ON        = 'F';
nml.NML_LAG.LAG_START_FILE   = 'lag_init.nc';
nml.NML_LAG.LAG_OUT_FILE     = 'lag_out.nc';
nml.NML_LAG.LAG_FIRST_OUT    = 'cycle=0';
nml.NML_LAG.LAG_RESTART_FILE = 'junk.nc';
nml.NML_LAG.LAG_OUT_INTERVAL = 'cycle=30';
nml.NML_LAG.LAG_SCAL_CHOICE  = 'none';
%/
%%
nml.NML_ADDITIONAL_MODELS = [];
nml.NML_ADDITIONAL_MODELS.DATA_ASSIMILATION       = 'F';
nml.NML_ADDITIONAL_MODELS.DATA_ASSIMILATION_FILE  =    'none';%
nml.NML_ADDITIONAL_MODELS.BIOLOGICAL_MODEL        = 'F';
nml.NML_ADDITIONAL_MODELS.STARTUP_BIO_TYPE        = 'observed';%
switch conf.version
    case 'ver4.0'
    case 'ver4.0-ersem'
        nml.NML_ADDITIONAL_MODELS.FABM_MODEL            = 'F';
end%/
nml.NML_ADDITIONAL_MODELS.SEDIMENT_MODEL          = 'F';
nml.NML_ADDITIONAL_MODELS.SEDIMENT_MODEL_FILE     = 'none';%
nml.NML_ADDITIONAL_MODELS.SEDIMENT_PARAMETER_TYPE = 'none';%
nml.NML_ADDITIONAL_MODELS.SEDIMENT_PARAMETER_FILE = 'none';%
nml.NML_ADDITIONAL_MODELS.BEDFLAG_TYPE            = 'none';%
nml.NML_ADDITIONAL_MODELS.BEDFLAG_FILE            = 'none';%
nml.NML_ADDITIONAL_MODELS.ICING_MODEL             = 'F';
nml.NML_ADDITIONAL_MODELS.ICING_FORCING_FILE      = 'none';%
nml.NML_ADDITIONAL_MODELS.ICING_FORCING_KIND      = 'none';%
nml.NML_ADDITIONAL_MODELS.ICING_AIR_TEMP          = 0.0000000E+00;%
fmt.NML_ADDITIONAL_MODELS.ICING_AIR_TEMP.format          = '%10.6f';%
nml.NML_ADDITIONAL_MODELS.ICING_WSPD              = 0.0000000E+00;%
fmt.NML_ADDITIONAL_MODELS.ICING_WSPD.format              = '%10.6f';%
nml.NML_ADDITIONAL_MODELS.ICE_MODEL               = 'F';
nml.NML_ADDITIONAL_MODELS.ICE_FORCING_FILE        = 'none';%
nml.NML_ADDITIONAL_MODELS.ICE_FORCING_KIND        = 'none';%
nml.NML_ADDITIONAL_MODELS.ICE_SEA_LEVEL_PRESSURE  = 0.0000000E+00;%
fmt.NML_ADDITIONAL_MODELS.ICE_SEA_LEVEL_PRESSURE.format  = '%10.6f';%
nml.NML_ADDITIONAL_MODELS.ICE_AIR_TEMP            = 0.0000000E+00;%
fmt.NML_ADDITIONAL_MODELS.ICE_AIR_TEMP.format            = '%10.6f';%
nml.NML_ADDITIONAL_MODELS.ICE_SPEC_HUMIDITY       = 0.0000000E+00;%
fmt.NML_ADDITIONAL_MODELS.ICE_SPEC_HUMIDITY.format       = '%10.6f';%
nml.NML_ADDITIONAL_MODELS.ICE_SHORTWAVE           = 0.0000000E+00;%
fmt.NML_ADDITIONAL_MODELS.ICE_SHORTWAVE.format           = '%10.6f';%
nml.NML_ADDITIONAL_MODELS.ICE_CLOUD_COVER         = 0.0000000E+00;
fmt.NML_ADDITIONAL_MODELS.ICE_CLOUD_COVER.format         = '%10.6f';
%/
%%

nml.NML_PROBES = [];
nml.NML_PROBES.PROBES_ON = 'F';
nml.NML_PROBES.PROBES_NUMBER = 56;%
fmt.NML_PROBES.PROBES_NUMBER.format = '%u';%
nml.NML_PROBES.PROBES_FILE = [conf.casename '_probes.nml'];
%/
%%
nml.NML_STATION_TIMESERIES = [];
nml.NML_STATION_TIMESERIES.OUT_STATION_TIMESERIES_ON = 'F';
nml.NML_STATION_TIMESERIES.STATION_FILE              = [conf.casename '_station.dat'];%
nml.NML_STATION_TIMESERIES.LOCATION_TYPE             = 'node';%
nml.NML_STATION_TIMESERIES.OUT_ELEVATION             = 'F';
nml.NML_STATION_TIMESERIES.OUT_VELOCITY_3D           = 'F';
nml.NML_STATION_TIMESERIES.OUT_VELOCITY_2D           = 'F';
nml.NML_STATION_TIMESERIES.OUT_WIND_VELOCITY         = 'F';
nml.NML_STATION_TIMESERIES.OUT_SALT_TEMP             = 'F';
nml.NML_STATION_TIMESERIES.OUT_INTERVAL              = 'seconds= 360.0';
%/
%%
switch conf.version
    case 'ver4.0'
    case 'ver4.0-ersem'
        nml.NML_FABM = [];
        nml.NML_FABM.STARTUP_FABM_TYPE = 'set values';
        nml.NML_FABM.OFFLINE_FABM_FILE=  [conf.casename '_offline.nc'];%
        nml.NML_FABM.USE_FABM_BOTTOM_THICKNESS= 'F';
        nml.NML_FABM.USE_FABM_SALINITY='F';
        nml.NML_FABM.FABM_DEBUG='F';
        nml.NML_FABM.FABM_DIAG_OUT='T';
end
%/


%%
nml.NML_NESTING = [];
nml.NML_NESTING.NESTING_ON = 'F';
nml.NML_NESTING.NESTING_BLOCKSIZE= 10;
fmt.NML_NESTING.NESTING_BLOCKSIZE.format= '%u';
nml.NML_NESTING.NESTING_TYPE= 3;
fmt.NML_NESTING.NESTING_TYPE.format= '%u';
nml.NML_NESTING.NESTING_FILE_NAME=[conf.casename '_nest.nc'];
%/
%%
nml.NML_NCNEST = [];
nml.NML_NCNEST.NCNEST_ON = 'F';
nml.NML_NCNEST.NCNEST_BLOCKSIZE= 20;
fmt.NML_NCNEST.NCNEST_BLOCKSIZE.format= '%u';
nml.NML_NCNEST.NCNEST_NODE_FILES=[conf.casename '_nodes.dat'];
nml.NML_NCNEST.NCNEST_OUT_INTERVAL='seconds= 900.0';
%/
%%
nml.NML_NCNEST_WAVE = [];
nml.NML_NCNEST_WAVE.NCNEST_ON_WAVE  = 'F';
nml.NML_NCNEST_WAVE.NCNEST_TYPE_WAVE     = 'spectral density'; %! or 'wave parameters'
nml.NML_NCNEST_WAVE.NCNEST_BLOCKSIZE_WAVE   =          -1;%
fmt.NML_NCNEST_WAVE.NCNEST_BLOCKSIZE_WAVE.format   =          '%i';%
nml.NML_NCNEST_WAVE.NCNEST_NODE_FILES_WAVE  = 'none';
%/
%%
nml.NML_BOUNDSCHK = [];
nml.NML_BOUNDSCHK.BOUNDSCHK_ON  = 'F';
nml.NML_BOUNDSCHK.CHK_INTERVAL  = 1;
fmt.NML_BOUNDSCHK.CHK_INTERVAL.format  = '%u';
nml.NML_BOUNDSCHK.VELOC_MAG_MAX = 6.5   ;
fmt.NML_BOUNDSCHK.VELOC_MAG_MAX.format = '%5.2f'   ;
nml.NML_BOUNDSCHK.ZETA_MAG_MAX  = 10.  ;
fmt.NML_BOUNDSCHK.ZETA_MAG_MAX.format  =  '%5.2f'  ;
nml.NML_BOUNDSCHK.TEMP_MAX      = 30.;
fmt.NML_BOUNDSCHK.TEMP_MAX.format      =  '%5.2f';
nml.NML_BOUNDSCHK.TEMP_MIN      = -4.;
fmt.NML_BOUNDSCHK.TEMP_MIN.format      =  '%5.2f';
nml.NML_BOUNDSCHK.SALT_MAX      = 40.;
fmt.NML_BOUNDSCHK.SALT_MAX.format      =  '%5.2f';
nml.NML_BOUNDSCHK.SALT_MIN      = -.5 ;
fmt.NML_BOUNDSCHK.SALT_MIN.format      = '%5.2f' ;
%/
%%
nml.NML_DYE_RELEASE = [];
nml.NML_DYE_RELEASE.DYE_ON	= 'F';
nml.NML_DYE_RELEASE.DYE_RELEASE_START	= '2046-02-01 00:00:00';%
nml.NML_DYE_RELEASE.DYE_RELEASE_STOP	= '2046-03-01 00:00:00' ;%
nml.NML_DYE_RELEASE.KSPE_DYE	= 1;%
fmt.NML_DYE_RELEASE.KSPE_DYE.format	= '%u';%
nml.NML_DYE_RELEASE.MSPE_DYE	= 1;%
fmt.NML_DYE_RELEASE.MSPE_DYE.format	= '%u';%
nml.NML_DYE_RELEASE.K_SPECIFY	= 1;%
fmt.NML_DYE_RELEASE.K_SPECIFY.format	= '%u';%
nml.NML_DYE_RELEASE.M_SPECIFY	= 8187;%
fmt.NML_DYE_RELEASE.M_SPECIFY.format	= '%u';%
nml.NML_DYE_RELEASE.DYE_SOURCE_TERM = 4500.0 ;
fmt.NML_DYE_RELEASE.DYE_SOURCE_TERM.format =  '%10.2f' ;
%%
nml.NML_PWP = [];
nml.NML_PWP.UPPER_DEPTH_LIMIT=20.00000;
fmt.NML_PWP.UPPER_DEPTH_LIMIT.format='%5.2f' ;
nml.NML_PWP.LOWER_DEPTH_LIMIT=200.0000;
fmt.NML_PWP.LOWER_DEPTH_LIMIT.format='%5.2f' ;
nml.NML_PWP.VERTICAL_RESOLUTION=1.000000;
fmt.NML_PWP.VERTICAL_RESOLUTION.format='%5.2f' ;
nml.NML_PWP.BULK_RICHARDSON=0.6500000;
fmt.NML_PWP.BULK_RICHARDSON.format='%5.2f' ;
nml.NML_PWP.GRADIENT_RICHARDSON=0.2500000;
fmt.NML_PWP.GRADIENT_RICHARDSON.format='%5.2f' ;

%%
nml.NML_SST_ASSIMILATION = [];
nml.NML_SST_ASSIMILATION.SST_ASSIM= 'F';
nml.NML_SST_ASSIMILATION.SST_ASSIM_FILE = [conf.casename '_sst.nc'];%
nml.NML_SST_ASSIMILATION.SST_RADIUS = 0.0000000E+00;
fmt.NML_SST_ASSIMILATION.SST_RADIUS.format = '%12.6f' ;
nml.NML_SST_ASSIMILATION.SST_WEIGHT_MAX = 1.0000000E+00;
fmt.NML_SST_ASSIMILATION.SST_WEIGHT_MAX.format = '%5.5f' ;
nml.NML_SST_ASSIMILATION.SST_TIMESCALE = 0.0000000E+00;
fmt.NML_SST_ASSIMILATION.SST_TIMESCALE.format = '%12.6f' ;
nml.NML_SST_ASSIMILATION.SST_TIME_WINDOW = 0.0000000E+00;
fmt.NML_SST_ASSIMILATION.SST_TIME_WINDOW.format = '%12.6f' ;
nml.NML_SST_ASSIMILATION.SST_N_PER_INTERVAL = 0;
fmt.NML_SST_ASSIMILATION.SST_N_PER_INTERVAL.format = '%u';%
%%
nml.NML_SSTGRD_ASSIMILATION = [];
nml.NML_SSTGRD_ASSIMILATION.SSTGRD_ASSIM = 'F';
nml.NML_SSTGRD_ASSIMILATION.SSTGRD_ASSIM_FILE = [conf.casename '_sstgrd.nc'];%sst-2005_1km.nc;
nml.NML_SSTGRD_ASSIMILATION.SSTGRD_WEIGHT_MAX = 0.5000000E+00;
nml.NML_SSTGRD_ASSIMILATION.SSTGRD_TIMESCALE = 0.00010000E+00;
nml.NML_SSTGRD_ASSIMILATION.SSTGRD_TIME_WINDOW = 1.0000000E+00; % This is in hours and not in seconds as stated in the manual
nml.NML_SSTGRD_ASSIMILATION.SSTGRD_N_PER_INTERVAL = 24.0 ;
fmt.NML_SSTGRD_ASSIMILATION.SSTGRD_WEIGHT_MAX.format = '%12.6f' ;
fmt.NML_SSTGRD_ASSIMILATION.SSTGRD_TIMESCALE.format = '%12.6f' ;
fmt.NML_SSTGRD_ASSIMILATION.SSTGRD_TIME_WINDOW.format = '%12.6f' ;
fmt.NML_SSTGRD_ASSIMILATION.SSTGRD_N_PER_INTERVAL.format = '%5.2f' ;

%%
nml.NML_SSHGRD_ASSIMILATION = [];
nml.NML_SSHGRD_ASSIMILATION.SSHGRD_ASSIM    = 'F';
nml.NML_SSHGRD_ASSIMILATION.SSHGRD_ASSIM_FILE       = [conf.casename '_sshgrd.nc'];%aqua_v13_sshgrd.nc;
nml.NML_SSHGRD_ASSIMILATION.SSHGRD_WEIGHT_MAX       =  0.000000000000000E+000;
nml.NML_SSHGRD_ASSIMILATION.SSHGRD_TIMESCALE        =  0.000000000000000E+000;
nml.NML_SSHGRD_ASSIMILATION.SSHGRD_TIME_WINDOW      =  0.000000000000000E+000;
nml.NML_SSHGRD_ASSIMILATION.SSHGRD_N_PER_INTERVAL   =           0;
fmt.NML_SSHGRD_ASSIMILATION.SSHGRD_WEIGHT_MAX.format       =  '%12.6f' ;
fmt.NML_SSHGRD_ASSIMILATION.SSHGRD_TIMESCALE.format        =  '%12.6f' ;
fmt.NML_SSHGRD_ASSIMILATION.SSHGRD_TIME_WINDOW.format      =  '%12.6f' ;
fmt.NML_SSHGRD_ASSIMILATION.SSHGRD_N_PER_INTERVAL.format   =           '%u';%
%%
nml.NML_TSGRD_ASSIMILATION = [];
nml.NML_TSGRD_ASSIMILATION.TSGRD_ASSIM     = 'F';
nml.NML_TSGRD_ASSIMILATION.TSGRD_ASSIM_FILE        = [conf.casename '_tsgrd.nc'];%aqua_v13_tsgrd.nc;
nml.NML_TSGRD_ASSIMILATION.TSGRD_WEIGHT_MAX        =  0.000000000000000E+000;
nml.NML_TSGRD_ASSIMILATION.TSGRD_TIMESCALE =  0.000000000000000E+000;
nml.NML_TSGRD_ASSIMILATION.TSGRD_TIME_WINDOW       =  0.000000000000000E+000;
nml.NML_TSGRD_ASSIMILATION.TSGRD_N_PER_INTERVAL    =           0;
fmt.NML_TSGRD_ASSIMILATION.TSGRD_WEIGHT_MAX.format        =  '%12.6f' ;
fmt.NML_TSGRD_ASSIMILATION.TSGRD_TIMESCALE.format =  '%12.6f' ;
fmt.NML_TSGRD_ASSIMILATION.TSGRD_TIME_WINDOW.format       =  '%12.6f' ;
fmt.NML_TSGRD_ASSIMILATION.TSGRD_N_PER_INTERVAL.format    =           '%u';%
%%
nml.NML_CUR_NGASSIMILATION = [];
nml.NML_CUR_NGASSIMILATION.CUR_NGASSIM     = 'F';
nml.NML_CUR_NGASSIMILATION.CUR_NGASSIM_FILE        = [conf.casename '_cur.nc'];%aqua_v13_cur;
nml.NML_CUR_NGASSIMILATION.CUR_NG_RADIUS   =  0.000000000000000E+000;
nml.NML_CUR_NGASSIMILATION.CUR_GAMA        =  0.000000000000000E+000;
nml.NML_CUR_NGASSIMILATION.CUR_GALPHA      =  0.000000000000000E+000;
nml.NML_CUR_NGASSIMILATION.CUR_NG_ASTIME_WINDOW    =  0.000000000000000E+000;
fmt.NML_CUR_NGASSIMILATION.CUR_NG_RADIUS.format   =  '%12.6f' ;
fmt.NML_CUR_NGASSIMILATION.CUR_GAMA.format        =  '%12.6f' ;
fmt.NML_CUR_NGASSIMILATION.CUR_GALPHA.format      =  '%12.6f' ;
fmt.NML_CUR_NGASSIMILATION.CUR_NG_ASTIME_WINDOW.format    =  '%12.6f' ;
%%
nml.NML_CUR_OIASSIMILATION = [];
nml.NML_CUR_OIASSIMILATION.CUR_OIASSIM     = 'F';
nml.NML_CUR_OIASSIMILATION.CUR_OIASSIM_FILE        = [conf.casename '_curoi.nc'];%aqua_v13_cur;
nml.NML_CUR_OIASSIMILATION.CUR_OI_RADIUS   =  0.000000000000000E+000;
nml.NML_CUR_OIASSIMILATION.CUR_OIGALPHA    =  0.000000000000000E+000;
nml.NML_CUR_OIASSIMILATION.CUR_OI_ASTIME_WINDOW    =  0.000000000000000E+000;
nml.NML_CUR_OIASSIMILATION.CUR_N_INFLU     =           0;
nml.NML_CUR_OIASSIMILATION.CUR_NSTEP_OI    =                     0;
fmt.NML_CUR_OIASSIMILATION.CUR_OI_RADIUS.format   =  '%12.6f' ;
fmt.NML_CUR_OIASSIMILATION.CUR_OIGALPHA.format    = '%12.6f' ;
fmt.NML_CUR_OIASSIMILATION.CUR_OI_ASTIME_WINDOW.format    =  '%12.6f' ;
fmt.NML_CUR_OIASSIMILATION.CUR_N_INFLU.format     =           '%u';%
fmt.NML_CUR_OIASSIMILATION.CUR_NSTEP_OI.format    =                    '%u';%
%%
nml.NML_TS_NGASSIMILATION = [];
nml.NML_TS_NGASSIMILATION.TS_NGASSIM      = 'F';
nml.NML_TS_NGASSIMILATION.TS_NGASSIM_FILE = [conf.casename '_ts.nc'];%aqua_v13_ts;
nml.NML_TS_NGASSIMILATION.TS_NG_RADIUS    =  0.000000000000000E+000;
nml.NML_TS_NGASSIMILATION.TS_GAMA =  0.000000000000000E+000;
nml.NML_TS_NGASSIMILATION.TS_GALPHA       =  0.000000000000000E+000;
nml.NML_TS_NGASSIMILATION.TS_NG_ASTIME_WINDOW     =  0.000000000000000E+000;
fmt.NML_TS_NGASSIMILATION.TS_NG_RADIUS.format    =  '%12.6f' ;
fmt.NML_TS_NGASSIMILATION.TS_GAMA.format = '%12.6f' ;
fmt.NML_TS_NGASSIMILATION.TS_GALPHA.format       =  '%12.6f' ;
fmt.NML_TS_NGASSIMILATION.TS_NG_ASTIME_WINDOW.format     =  '%12.6f' ;
%%
nml.NML_TS_OIASSIMILATION = [];
nml.NML_TS_OIASSIMILATION.TS_OIASSIM      = 'F';
nml.NML_TS_OIASSIMILATION.TS_OIASSIM_FILE = [conf.casename '_tsoi.nc'];%aqua_v13_ts;
nml.NML_TS_OIASSIMILATION.TS_OI_RADIUS    =  0.000000000000000E+000;
nml.NML_TS_OIASSIMILATION.TS_OIGALPHA     =  0.000000000000000E+000;
nml.NML_TS_OIASSIMILATION.TS_OI_ASTIME_WINDOW     =  0.000000000000000E+000;
nml.NML_TS_OIASSIMILATION.TS_MAX_LAYER    =           0;
nml.NML_TS_OIASSIMILATION.TS_N_INFLU      =           0,
nml.NML_TS_OIASSIMILATION.TS_NSTEP_OI     =                     0;
fmt.NML_TS_OIASSIMILATION.TS_OI_RADIUS.format    =  '%12.6f' ;
fmt.NML_TS_OIASSIMILATION.TS_OIGALPHA.format     =  '%12.6f' ;
fmt.NML_TS_OIASSIMILATION.TS_OI_ASTIME_WINDOW.format     =  '%12.6f' ;
fmt.NML_TS_OIASSIMILATION.TS_MAX_LAYER.format    =          '%u';%
fmt.NML_TS_OIASSIMILATION.TS_N_INFLU.format      =           '%u';%
fmt.NML_TS_OIASSIMILATION.TS_NSTEP_OI.format     =                     '%u';%

return
