Description of ST_Dstar
Home > utilities > ST_Dstar.m
ST_Dstar
PURPOSE
Calculate non-dimensional grain size D*
SYNOPSIS
function [dstar] = ST_Dstar(d,varargin)
DESCRIPTION
 Calculate non-dimensional grain size D*
 function [dstar] = ST_Dstar(d,varargin)
 DESCRIPTION:
    Convert grain size from d (m) to dimensionless D
 INPUT:
    d: sediment grain size in m
    [optional] 'temperature' = temperature of the seawater in C [default=10]
    [optional] 'salinity'    = salinity of seawater in PSU      [default=35]
    [optional] 'sdens'       = sediment density in kg/m^3       [default=2650]
 OUTPUT:
    Dstar:  nondimensional grain size
 EXAMPLE USAGE
    dstar = ST_Dstar(.0005,'temperature',10,'salinity',35,'sdens',2650)
 Author(s):
    Geoff Cowles (University of Massachusetts Dartmouth)
    Pierre Cazenave (Plymouth Marine Laboratory)
 Revision history
    2017-03-27 Add support for matrices and some minor syntax changes.
==============================================================================
CROSS-REFERENCE INFORMATION
This function calls:
SW_Density SW_Density Density of sea water
SW_Kviscosity Calculates the kinemtic viscosity [m^2/s] from the dynamic viscosity and
This function is called by:
ST_example Example usage of Sediment Toolbox
ST_summary Print summary for stats of particle diameter d (m)
ST_taucr Calculate critical shear stress in Pascals (equivalent to N/m^2)
ST_wset Calculate settling velocity of particle diameter d (m) in m/s
SOURCE CODE
function [dstar] = ST_Dstar(d,varargin)
% Calculate non-dimensional grain size D*
%
% function [dstar] = ST_Dstar(d,varargin)
%
% DESCRIPTION:
%    Convert grain size from d (m) to dimensionless D
%
% INPUT:
%    d: sediment grain size in m
%    [optional] 'temperature' = temperature of the seawater in C [default=10]
%    [optional] 'salinity'    = salinity of seawater in PSU      [default=35]
%    [optional] 'sdens'       = sediment density in kg/m^3       [default=2650]
%
% OUTPUT:
%    Dstar:  nondimensional grain size
%
% EXAMPLE USAGE
%    dstar = ST_Dstar(.0005,'temperature',10,'salinity',35,'sdens',2650)
%
% Author(s):
%    Geoff Cowles (University of Massachusetts Dartmouth)
%    Pierre Cazenave (Plymouth Marine Laboratory)
%
% Revision history
%    2017-03-27 Add support for matrices and some minor syntax changes.
%
%==============================================================================
global ftbverbose
[~, subname] = fileparts(mfilename('fullpath'));
if ftbverbose
    fprintf('\nbegin : %s\n', subname)
end
% constants
grav  = 9.8106;   %g
T     = 10;       %T (C)
S     = 35;       %S (PSU)
sdens = 2650;     %sediment density in kg/m^3
% parse arguments
for i=1:2:length(varargin)-1
        keyword  = lower(varargin{i});
        if( ~ischar(keyword) )
                error('incorrect usage of ST_Dstar')
        end;
        switch(keyword(1:3))
        case 'tem'
             T = varargin{i+1};
        case 'sal'
             S = varargin{i+1};
        case 'sde'
             sdens = varargin{i+1};
        otherwise
                error(['Can''t understand value for:' keyword]);
        end; %switch keyword
end;
% calculate nu
nu = SW_Kviscosity(T,S);
% calculate rho
dens = SW_Density(T,S);
% calculate dstar
if isscalar(dens)
    s = sdens/dens;
    dstar = ([grav*(s-1)/(nu^2)])^(1/3)*d;
else
    s = sdens ./ dens;
    dstar = ([grav*(s-1)./(nu.^2)]).^(1/3).*d;
end
if ftbverbose
    fprintf('end   : %s\n', subname)
end