Description of SW_Kviscosity
Home > utilities > SW_Kviscosity.m
SW_Kviscosity
PURPOSE
Calculates the kinemtic viscosity [m^2/s] from the dynamic viscosity and
SYNOPSIS
function new = SW_Kviscosity(T,S)
DESCRIPTION
 Calculates the kinemtic viscosity [m^2/s] from the dynamic viscosity and
 density functions
CROSS-REFERENCE INFORMATION
This function calls:
SW_Density SW_Density Density of sea water
SW_Viscosity SW_Viscosity Dynamic viscosity of seawater
This function is called by:
ST_Dstar Calculate non-dimensional grain size D*
ST_wset Calculate settling velocity of particle diameter d (m) in m/s
calc_tauw DESCRIPTION:
check_wset Calculate settling velocity of particle diameter d (m) in m/s
SOURCE CODE
function new = SW_Kviscosity(T,S)
% Calculates the kinemtic viscosity [m^2/s] from the dynamic viscosity and
% density functions
mu = SW_Viscosity(T,S);
rho = SW_Density(T,S);
new = mu./rho;
end